name: CI Run
on:
  workflow_run:
    workflows: ["Semgrep Scan"]
    types:
      - completed
  

jobs:
  ci-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: running ci
        run: echo "CI shit here"
