name: CI Run
on:
  workflow_run:
    workflows: ["Semgrep Scan"]
    types:
      - completed
  

jobs:
  ci-run:
    runs-on: ubuntu-latest

    steps:
      - name: print semgrep-status
        run: echo "semgrep-scan_workflow_status=${{ github.event.workflow_run.conclusion }}"

      - name: running ci
        run: echo "CI shit here"
