name: CI Run
on:
  workflow_run:
    workflows: ["Semgrep Scan"]
    types:
      - completed

jobs:
  ci-run:
    if: ${{ github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: running ci
        run: echo "CI shit here"
