name: Semgrep Scan
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: clone code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: baseline commit
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "BASELINE_COMMIT=$(git merge-base origin/$GITHUB_BASE_REF HEAD)" >> $GITHUB_ENV
          else
            echo "BASELINE_COMMIT=$GITHUB_EVENT_BEFORE" >> $GITHUB_ENV
          fi
      - name: semgrep scan
        run: |
          semgrep scan --error --metrics=off --baseline-commit "$BASELINE_COMMIT" --config="p/default"
