name: Security Scan
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep Scan
        continue-on-error: true
        id: semgrep
        run: |
          semgrep scan --error --metrics=off --config="p/default" --config .semgrep/
          echo "exit_code=$?" >> $GITHUB_ENV

      - name: Debug exit code
        run: |
          echo "exit_code=$exit_code"

      - name: Send Slack Alert on Failure
        if: ${{ env.exit_code == '1' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "*CI Security Scan - Failed*",
            "attachments": [
              {
                "color": "#ff0000",
                "fields": [
                  { "title": "Repository", "value": "${{ github.repository }}", "short": true },
                  { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                  { "title": "Commit", "value": "${{ github.sha }}", "short": true },
                  {
                    "title": "Results",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Job logs>",
                    "short": false
                  }
                ],
                "footer": "Tag <@${{ secrets.MY_SLACK_USER }}> in case of any security issues",
                "ts": "$(date +%s)"
              }
            ]
          }' ${{ secrets.MY_SLACK_WEBHOOK_URL }}
